### ISSUE TITLE
highlight Visual guibg

### ISSUE THREAD

**Issue by hackedWifi** [savq/melange#15]
Thank you for the amazing colorscheme. I feel like the Visual selection is hard to see with the defined color. I have tried to add a guifg=white to make my eyes help to see where the visual selection ends.
It is hard for my eyes to really see where the visual selection starts and ends with the current color.

**Comment by savq** [comment]
Hey @hackedWifi, I agree that the visual selection wasn't very visually distinctive (you're not the first one to comment on it).

I've updated the it to make it brighter.
