### ISSUE TITLE
Option to disable font variants

### ISSUE THREAD

**Issue by andynameistaken** [savq/melange#16]
Could you provide simple option that could be set in `init.vim` so it would disable italics?

**Comment by savq** [comment]
Hey @andynameistaken,

Melange compiles Lua to vimscript to make the colorscheme usable in vim8. Adding this to the compile step would be kind of tedious.

I could however, add an option for the Lua file, but you'd have to use Lush yourself to load the colorscheme:
```
lua require("lush")(require("melange"))
```

Maybe you could set your package manager to run `make` and compile a colorscheme without color variants.

I'm currently making rewriting some thing in the colorscheme, I'll add this after that, and check if compiling would work.

**Comment by savq** [comment]
I added this a couple of weeks ago but forgot to write a follow up.

You can now disable font variants by setting the global variable `melange_enable_font_variants` to 0, and sourcing the colorscheme with Lush. To make the change persistent, you should call `:lua require("melange.build").build()`.

In Lua:
```lua
function melange_no_variants()
    vim.g.melange_enable_font_variants = 0    -- disable font variants
    require("lush")                           -- make sure Lush is installed
    require("melange.build").build()          -- Compile to vimscript
end
```

You'd only need to call this function once. Afterwards, `:colorscheme melange` should set the colorscheme without font variants.

**Comment by andynameistaken** [comment]
Thanks for the option and for the theme in general - it is really nice thing between gruvbox and earthsong and fixes  visual issues of those two: it doesn't use red for 'normal' information (problem with gruvbox) and doesn't use white too much (earthsong)

**Comment by ahelwer** [comment]
I will say after trying out the recommended IBM Plex Mono font instead of the Consolas font, italics look much better. Here's Consolas:
![image](https://user-images.githubusercontent.com/718765/128098042-543383fa-180c-42c5-9657-06e1d624e12b.png)
vs. IBM Plex Mono:
![image](https://user-images.githubusercontent.com/718765/128098096-962fd711-6006-43b6-8793-5637ec6458ea.png)
