### ISSUE TITLE
Disable TSError underline in terminal

### ISSUE THREAD

**Issue by Samyak2** [savq/melange#21]
# The issue

Whenever treesitter fails to parse some program, the errors are highlighted using underlines. This is especially annoying when the code is valid, but treesitter does not recognize it. Here is an example where treesitter highlights ~80 lines of valid C code and the theme adds an underline to all of that:
![image](https://user-images.githubusercontent.com/34161949/131549122-5ea5499e-2290-43c2-9a22-1d3abfb46727.png)

This is annoying because it becomes difficult to differentiate between `i` and `j`, for example, when it's underlined. It generally makes it much harder to edit by underlining multiple lines.

# Possible solution

I temporarily solved this by removing `gui=undercurl` from the `TSError` highlight group in the compiled `melange.vim` file.

```
highlight TSError guifg=NONE guibg=NONE guisp=NONE gui=undercurl blend=NONE
```

to

```
highlight TSError guifg=NONE guibg=NONE guisp=NONE blend=NONE
```

---

In the lush code, I think the change would be removing this:

https://github.com/savq/melange/blob/aebc5256c8804ebad66676ab9ab591bed53170d9/lua/melange/init.lua#L261

# Thoughts?

Is this an appropriate solution for this problem?

---

Thank you for making this theme, I've been using this for some time now and really liked it :heart:

**Comment by savq** [comment]
Yeah, I'll probably be removing that soon.

For some grammars, error nodes behave nicely and highlights can be very informative, but for others the error nodes keep spreading and it becomes pretty useless.

I also noticed while having to read preprocessor heavy code 😅. It was so bad I made a note in the [nvim-treesitter docs](https://github.com/savq/nvim-treesitter/blob/d19d1da0be01e9b45d2e685c0ae31eab94332bec/doc/nvim-treesitter.txt#L499).


---

In the mean time you can add the following to your config:

```viml
augroup melange_fix
    au!
    au ColorScheme melange highlight! clear TSError
augroup END
```

**Comment by Samyak2** [comment]
That temporary fix works, thanks!
