### ISSUE TITLE
Document the palette or put the palette in a data file

### ISSUE THREAD

**Issue by spenserblack** [savq/melange#36]
I love this theme! I'd like to port this to some tools.
Would it be possible to document the palette, similar to what [gruvbox does](https://github.com/morhetz/gruvbox#palette)? This would help facilitate ports of this theme.

**Comment by spenserblack** [comment]
>I think having the palette in a json file might work for most people.

Sounds good! Updated the issue title.

**Comment by savq** [comment]
I added the json files to [./palette](../tree/v0.8.0/palette), altho this is still subject to change.

PS. `vim.json` doesn't format the output so you might want to use `jq` for that.
