### ISSUE TITLE
E423: Illegal argument: blend=NONE

### ISSUE THREAD

**Issue by halostatue** [savq/melange#4]
I am picking through a few colourschemes and found this one. I realize that it’s WIP, but your description suggests you’re trying to make this work on both Vim and Neovim.

Unfortunately `highlight` does not support `blend=` on Vim as of version 8.2

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  8 2021 07:21:32)
macOS version - x86_64
Included patches: 1-2576  
```

**Comment by savq** [comment]
Hey, thanks for lettign me know. I wasn't aware of that.

Melange doesn't use the `blend` property, so I just removed it altogether.

**Comment by halostatue** [comment]
Thanks!
