### ISSUE TITLE
Colorscheme doesn't work

### ISSUE THREAD

**Issue by EpsilonKu** [savq/melange#8]
Colorscheme doesn't work with my config. It work if I set :set background=light.

**Comment by spencergilbert** [comment]
Similarly having issues, not entirely sure why - if I revert back to using the v0.1.1 tag I'm not seeing any issues. Happy to help troubleshoot

**Comment by savq** [comment]
>  It work if I set :set background=light

So only the dark variant fails?

Last update I added the light variant, and split the vim colors definitions into two files. I left a dummy file (`colors/melange.vim`) that would point to the correct variant depending on `background`.

I'm not entirely sure why it fails tho. It was working on my machine™️ . I'll try writing both variants to the same file and see how it goes.

**Comment by spencergilbert** [comment]
I've got the joy of also moving from linux -> Mac (M1) so there might be some other environmental differences that are causing issues. I've got a free week coming up where I can lend a hand figuring out the issue, I originally assumed it was something Linux/MacOS related but now that I've _realized_ where the issue appears to be I can be more helpful.

(love the color scheme btw)

**Comment by savq** [comment]
@spencergilbert,  I made some commits to the `dev` branch. Could you check it and see if it's working the same as `v0.1.1`?

> (love the color scheme btw)

Thanks! 😄

**Comment by spencergilbert** [comment]
Just checked and everything looks right to me (MacOS, M1, Alacritty, Neovim), light and dark 👍

**Comment by savq** [comment]
Everything seems to be working for me too.

Having both light and dark hightlight definitions in the same file also means that changing `background` automatically changes the colorscheme, which is a nice plus.
